### ISSUE TITLE
Detect and remove the flat surface (table) from the pointcloud that is given to gpd

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [KavrakiLab/fetch_ros#2]

**Comment by BryceStevenWilley** [comment]
[This file](https://github.com/KavrakiLab/KinectCV/blob/master/extract_indicies.cpp) might help. It reads in a point cloud, segments out the most prominent planar surface from that cloud, removes that surface, and continues until most of the cloud is gone.

**Comment by ell0ry** [comment]
I'm going to try tackling this issue in a new separate repo.

**Comment by ChamzasKonstantinos** [comment]
This demo is currently abandoned
